// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9UmI2AtxOyyVwX-P9yKXudPBJUnT_m4s',
    appId: '1:1004885776986:web:cc02da7c77026af1e2d663',
    messagingSenderId: '1004885776986',
    projectId: 'goearn1',
    authDomain: 'goearn1.firebaseapp.com',
    storageBucket: 'goearn1.firebasestorage.app',
    measurementId: 'G-E22ZPCBWX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBowXj-L5mhiA6ohbG6NUXHvh1B01LDJL8',
    appId: '1:1004885776986:android:ad3783e10f653640e2d663',
    messagingSenderId: '1004885776986',
    projectId: 'goearn1',
    storageBucket: 'goearn1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbeBQ-Ur8WxsEf0tT84WUM4YzXJyYMU_o',
    appId: '1:1004885776986:ios:aabd157f4abf184ae2d663',
    messagingSenderId: '1004885776986',
    projectId: 'goearn1',
    storageBucket: 'goearn1.firebasestorage.app',
    androidClientId: '1004885776986-mrsnqt97th8do1enaep3ihl533vfnquu.apps.googleusercontent.com',
    iosClientId: '1004885776986-33lcfahoq6b9325ua4tkqcfgpj3tbfh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.goearn1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbeBQ-Ur8WxsEf0tT84WUM4YzXJyYMU_o',
    appId: '1:1004885776986:ios:aabd157f4abf184ae2d663',
    messagingSenderId: '1004885776986',
    projectId: 'goearn1',
    storageBucket: 'goearn1.firebasestorage.app',
    androidClientId: '1004885776986-mrsnqt97th8do1enaep3ihl533vfnquu.apps.googleusercontent.com',
    iosClientId: '1004885776986-33lcfahoq6b9325ua4tkqcfgpj3tbfh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.goearn1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9UmI2AtxOyyVwX-P9yKXudPBJUnT_m4s',
    appId: '1:1004885776986:web:cea4fb0fe30ce45ce2d663',
    messagingSenderId: '1004885776986',
    projectId: 'goearn1',
    authDomain: 'goearn1.firebaseapp.com',
    storageBucket: 'goearn1.firebasestorage.app',
    measurementId: 'G-VMFV1GX2V7',
  );

}